version: '3.9'
services:
  client:
    build:
      context: spotifytrendsapp.client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./spotifytrendsapp.client:/app      # mount local source into container
      - /app/node_modules                   # preserve container node_modules
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: SpotifyTrendsApp.Server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - topitems
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TopItemsService__BaseUrl=http://topitems:5000
  topitems:
    build:
      context: TopItemsService
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
