version: '3.9'
services:
  client:
    build:
      context: spotifytrendsapp.client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./spotifytrendsapp.client:/app      # mount local source into container
      - /app/node_modules                   # preserve container node_modules
  server:
    build:
      context: .
      dockerfile: SpotifyTrendsApp.Server/Dockerfile
    ports:
      - "5000:5000"
  topitems:
    build:
      context: TopItemsService
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
